# Generated by Django 3.2.3 on 2021-08-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_diet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
