# Generated by Django 3.2.3 on 2021-08-10 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_diet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='writer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
