# Generated by Django 3.2.5 on 2021-08-11 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_diet_writer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_work1', models.CharField(default='', max_length=30)),
                ('mon_work2', models.CharField(default='', max_length=30)),
                ('mon_work3', models.CharField(default='', max_length=30)),
                ('tue_work1', models.CharField(default='', max_length=30)),
                ('tue_work2', models.CharField(default='', max_length=30)),
                ('tue_work3', models.CharField(default='', max_length=30)),
                ('wed_work1', models.CharField(default='', max_length=30)),
                ('wed_work2', models.CharField(default='', max_length=30)),
                ('wed_work3', models.CharField(default='', max_length=30)),
                ('thr_work1', models.CharField(default='', max_length=30)),
                ('thr_work2', models.CharField(default='', max_length=30)),
                ('thr_work3', models.CharField(default='', max_length=30)),
                ('fri_work1', models.CharField(default='', max_length=30)),
                ('fri_work2', models.CharField(default='', max_length=30)),
                ('fri_work3', models.CharField(default='', max_length=30)),
                ('sat_work1', models.CharField(default='', max_length=30)),
                ('sat_work2', models.CharField(default='', max_length=30)),
                ('sat_work3', models.CharField(default='', max_length=30)),
                ('sun_work1', models.CharField(default='', max_length=30)),
                ('sun_work2', models.CharField(default='', max_length=30)),
                ('sun_work3', models.CharField(default='', max_length=30)),
                ('writer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
